# Generated by Django 4.1.9 on 2023-10-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eq', models.CharField(max_length=100)),
                ('dispo_eq', models.IntegerField()),
                ('start_hour_eq', models.CharField(max_length=100)),
                ('finish_hour_eq', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('start_hour', models.TimeField()),
                ('finish_hour', models.TimeField()),
                ('description', models.CharField(max_length=200)),
                ('etat', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dispo', models.IntegerField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
