# Generated by Django 4.1.9 on 2023-08-23 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dayoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(max_length=255)),
                ('nbdays', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('EMERGENCY LEAVE', 'EMMERGENCY LEAVE'), ('ANNUAL LEAVE', 'ANNUAL LEAVE'), ('PERSONAL LEAVE', 'PERSONAL LEAVE'), ('RECOVERY LEAVE', 'RECOVERY LEAVE')], max_length=255)),
                ('createdate', models.DateField()),
                ('startdate', models.DateField()),
                ('returndate', models.DateField()),
                ('motif', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('INPROGRESS', 'INPROGRESS'), ('DECLINED', 'DECLINED')], max_length=255)),
                ('backupperson', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='backupperson', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='dayoffcreator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
