# Generated by Django 4.0.3 on 2023-08-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='name',
            field=models.TextField(default='default', max_length=255),
        ),
    ]
