# Generated by Django 4.1.9 on 2023-09-04 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0002_dayoff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='createdate',
            field=models.DateField(default=datetime.date(2023, 9, 4)),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='motif',
            field=models.TextField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='nbdays',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='position',
            field=models.TextField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='returndate',
            field=models.DateField(default=datetime.date(2023, 9, 4)),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='startdate',
            field=models.DateField(default=datetime.date(2023, 9, 4)),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('INPROGRESS', 'INPROGRESS'), ('DECLINED', 'DECLINED')], default='INPROGRESS', max_length=255),
        ),
    ]
