# Generated by Django 4.1.9 on 2023-08-23 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remotework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('position', models.TextField(max_length=255)),
                ('nbdays', models.PositiveIntegerField()),
                ('createdate', models.DateField()),
                ('startdate', models.DateField()),
                ('returndate', models.DateField()),
                ('motif', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('INPROGRESS', 'INPROGRESS'), ('DECLINED', 'DECLINED')], max_length=255)),
                ('creator', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remoteworkplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('TO DO', 'TO DO'), ('INPROGRESS', 'INPROGRESS')], max_length=255)),
                ('request', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='remotework.remotework')),
            ],
        ),
    ]
