# Generated by Django 4.1.9 on 2023-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MG', 'manager'), ('SU', 'simple_user'), ('AD', 'admin'), ('RH', 'talent_management')], default='SU', max_length=2),
        ),
    ]
