# Generated by Django 4.1.9 on 2023-10-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_profile_photo_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dayoffamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ttamount',
            field=models.IntegerField(default=0),
        ),
    ]
