# Generated by Django 4.1.9 on 2023-08-23 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('equipment', models.CharField(choices=[('MICRO', 'MICRO'), ('TV1', 'TV1'), ('TV2', 'TV2')], max_length=255)),
                ('purpose', models.TextField(max_length=255)),
                ('createdate', models.DateField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('INPORGRESS', 'INPROGRESS')], max_length=255)),
                ('creator', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
